FROM ubuntu:latest

COPY HelloWorld.java HelloWorld.java

#it installs openssl/libssl/tzdata/libc6

RUN apt-get update && \
    apt-get install -y openjdk-11-jre-headless && \
    apt-get clean

ENV JAVA_HOME /usr

CMD ["java","HelloWorld.java"]
